version: '3.9'

services:
    CatalogDB:
        container_name: CatalogDB
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres  
            - POSTGRES_DB=CatalogDB
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_catalog:/var/lib/postgresql/data/ 

    CatalogAPI:
        container_name: CatalogAPI
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__Database=Server=CatalogDB;Port=5432;Database=CatalogDB;User Id=postgres;Password=postgres;Include Error Detail=true
        depends_on:
            - CatalogDB
        ports:
            - "6000:8080"
            - "6060:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
