version: '3.9'

name: e-shop-microservices

services:
    #Catalog Microservice
    CatalogDB:
        container_name: CatalogDB
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres  
            - POSTGRES_DB=CatalogDB
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_catalog:/var/lib/postgresql/data/ 

    CatalogAPI:
        container_name: CatalogAPI
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__Database=Server=CatalogDB;Port=5432;Database=CatalogDB;User Id=postgres;Password=postgres;Include Error Detail=true
        depends_on:
            - CatalogDB
        ports:
            - "6000:8080"
            - "6060:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    #Basket Microservice
    BasketDB:
        container_name: BasketDB
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres  
            - POSTGRES_DB=BasketDB
        restart: always
        ports:
            - "5433:5432"
        volumes:
            - postgres_basket:/var/lib/postgresql/data/

    BasketAPI:
        container_name: BasketAPI
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - ConnectionStrings__Database=Server=BasketDB;Port=5432;Database=BasketDB;User Id=postgres;Password=postgres;Include Error Detail=true
          - ConnectionStrings__Redis=RedisCache:6379
        depends_on:
            - BasketDB
            - RedisCache
        ports:
          - "6001:8080"
          - "6061:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    #Shared
    RedisCache:
        container_name: RedisCache
        restart: always
        ports:
            - "6379:6379"

  
