version: '3.9'

name: e-shop-microservices

services:
    #Catalog Microservice
    CatalogDB:
        container_name: Catalog.DB
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres  
            - POSTGRES_DB=CatalogDB
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_catalog:/var/lib/postgresql/data/ 

    CatalogAPI:
        container_name: Catalog.API
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__Database=Server=CatalogDB;Port=5432;Database=CatalogDB;User Id=postgres;Password=postgres;Include Error Detail=true
            - ElasticConfiguration__Uri=http://ElasticSearch:9200
        depends_on:
            - CatalogDB
        ports:
            - "6000:8080"
            - "6060:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    #Basket Microservice
    BasketDB:
        container_name: Basket.DB
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres  
            - POSTGRES_DB=BasketDB
        restart: always
        ports:
            - "5433:5432"
        volumes:
            - postgres_basket:/var/lib/postgresql/data/

    BasketAPI:
        container_name: Basket.API
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - ConnectionStrings__Database=Server=BasketDB;Port=5432;Database=BasketDB;User Id=postgres;Password=postgres;Include Error Detail=true
          - ConnectionStrings__Redis=RedisCache:6379
          - GrpcSettings__DiscountUrl=https://DiscountgRPC:8081
          - MessageBroker__Host=amqp://ecomerce-mq:5672
          - MessageBroker__UserName=guest
          - MessageBroker__Password=guest
          - ElasticConfiguration__Uri=http://ElasticSearch:9200
        depends_on:
            - BasketDB
            - RedisCache
            - DiscountgRPC
            - MessageBroker
        ports:
          - "6001:8080"
          - "6061:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
 
    #Discount Microservice
    DiscountgRPC:
        container_name: Discount.API
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - ConnectionStrings__Database=Data Source=DiscountDB
          - Kestrel__Endpoints__Http__Url=https://DiscountgRPC:8081
          - Kestrel__Endpoints__Http__Protocols=Http1AndHttp2"      
          - Kestrel__Endpoints__gRPC__Url=http://DiscountgRPC:8080
          - Kestrel__Endpoints__gRPC__Protocols=Http2
          - ElasticConfiguration__Uri=http://ElasticSearch:9200
        ports:
          - "6002:8080"
          - "6062:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    #Ordering Microservice
    OrderDB:
        container_name: Order.DB
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Test12345
        restart: always
        ports:
            - "1433:1433"

    OrderAPI:
        container_name: Order.API
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - ConnectionStrings__Database=Server=OrderDB;Database=OrderDB;User Id=sa;Password=Test12345;Encrypt=False;TrustServerCertificate=True
          - MessageBroker__Host=amqp://ecomerce-mq:5672
          - MessageBroker__UserName=guest
          - MessageBroker__Password=guest
          - FeatureManagement__OrderFullfilment=false
          - ElasticConfiguration__Uri=http://ElasticSearch:9200
        depends_on:
            - OrderDB
            - MessageBroker
        ports:
          - "6003:8080"
          - "6063:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    #ApiGateways
    ApiGatewayWeb:
        container_name: ApiGateway.Web
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - ElasticConfiguration__Uri=http://ElasticSearch:9200
        depends_on:
            - CatalogAPI 
            - BasketAPI 
            - OrderAPI
        ports:
          - "6004:8080"
          - "6064:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro    
       
    #Clients
    WebApp:
        container_name: WebApp
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - ApiSettings__GatewayAddress=http://ApiGatewayWeb:8080
          - ElasticConfiguration__Uri=http://ElasticSearch:9200
        ports:
          - "6005:8080"
          - "6065:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    WebAppMonitoring:
        container_name: WebApp.Monitoring
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          - ASPNETCORE_HTTPS_PORTS=8081
          - HealthChecksUI__HealthChecks__0__Name="Catalog API"
          - HealthChecksUI__HealthChecks__0__Uri=http://CatalogAPI:8080/health
          - HealthChecksUI__HealthChecks__1__Name="Basket API"
          - HealthChecksUI__HealthChecks__1__Uri=http://BasketAPI:8080/health
          # - HealthChecksUI__HealthChecks__2__Name="Discount API"
          # - HealthChecksUI__HealthChecks__2__Uri=http://DiscountgRPC:8080/health
          - HealthChecksUI__HealthChecks__3__Name="Order API"
          - HealthChecksUI__HealthChecks__3__Uri=http://OrderAPI:8080/health
          - HealthChecksUI__HealthChecks__4__Name="API Gateway Web"
          - HealthChecksUI__HealthChecks__4__Uri=http://ApiGatewayWeb:8080/health
          # - HealthChecksUI__HealthChecks__5__Name="WebApp"
          # - HealthChecksUI__HealthChecks__5__Uri=http://WebApp:8080/health
        ports:
          - "6006:8080"
          - "6066:8081"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    #Shared
    RedisCache:
        container_name: RedisCache
        restart: always
        ports:
            - "6379:6379"
 
    MessageBroker:
        container_name: MessageBroker
        hostname: ecomerce-mq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    #Monitoring
    ElasticSearch:
        container_name: ElasticSearch
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
        restart: always
        environment:
             - xpack.security.enabled=false
             - discovery.type=single-node
        mem_limit: ${ES_MEM_LIMIT}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            
    Kibana:
       container_name: Kibana
       depends_on:
         - ElasticSearch
       volumes:
         - kibana_data:/usr/share/kibana/data
       ports:
         - 5601:5601
       restart: always
       environment:
         - ELASTICSEARCH_HOSTS=http://ElasticSearch:9200
       mem_limit: ${KB_MEM_LIMIT}
