version: '3.9'

name: e-shop-microservices

services:
 #Catalog
 CatalogDB:
  image: postgres

 CatalogAPI:
  image: ${DOCKER_REGISTRY-}catalogapi
  build:
   context: .
   dockerfile: Services/Catalog/EShopMicroservices.Services.Catalog.API/Dockerfile

 #Basket
 BasketDB:
  image: postgres

 BasketAPI:
  image: ${DOCKER_REGISTRY-}basketapi
  build:
    context: .
    dockerfile: Services/Basket/EShopMicroservices.Services.Basket.API/Dockerfile

 #Shared
 RedisCache:
  image: redis


volumes:
 postgres_catalog:
 postgres_basket:


