version: '3.9'

name: e-shop-microservices

services:
 CatalogDB:
  image: postgres

 CatalogAPI:
  image: ${DOCKER_REGISTRY-}catalogapi
  build:
   context: .
   dockerfile: Services/Catalog/EShopMicroservices.Services.Catalog.API/Dockerfile

volumes:
 postgres_catalog:

