version: '3.9'

name: e-shop-microservices

services:
 #Catalog
 CatalogDB:
  image: postgres

 CatalogAPI:
  image: ${DOCKER_REGISTRY-}catalogapi
  build:
   context: .
   dockerfile: Services/Catalog/EShopMicroservices.Services.Catalog.API/Dockerfile

 #Basket
 BasketDB:
  image: postgres

 BasketAPI:
  image: ${DOCKER_REGISTRY-}basketapi
  build:
    context: .
    dockerfile: Services/Basket/EShopMicroservices.Services.Basket.API/Dockerfile

 #Ordering
 OrderDB:
  image: mcr.microsoft.com/mssql/server

 OrderAPI:
  image: ${DOCKER_REGISTRY-}orderapi
  build:
   context: .
   dockerfile: Services/Ordering/EShopMicroservices.Services.Ordering.API/Dockerfile

 #Discount
 DiscountgRPC:
  image: ${DOCKER_REGISTRY-}discountgrpc
  build:
    context: .
    dockerfile: Services/Discount/EShopMicroservices.Services.Discount.Grpc/Dockerfile

 #Shared
 RedisCache:
  image: redis

 MessageBroker:
  image: rabbitmq:management


volumes:
 postgres_catalog:
 postgres_basket:




